### PR TITLE
add appveyor

### PR DESCRIPTION
**Pull request by nooperpudd**
add appveyor ci

### CODE REVIEW

**Comment by nooperpudd** [comment]
@justadudewhohacks  add appveryor CI, but when to run npm test, raise an exception. would u have time to see the problems? https://ci.appveyor.com/project/nooperpudd/opencv4nodejs

**Comment by justadudewhohacks** [comment]
Awesome, thanks for this PR! I will look into appveyor asap and then merge this PR. I assume it works similar to travis, right?

**Comment by nooperpudd** [comment]
@justadudewhohacks Yes, the workflow run the same way.

**Comment by justadudewhohacks** [comment]
Some minor remarks:

1. I think chocolatey does not have opencv 3.3.1 in it's registry yet, we might have to skip these for the moment. 

2. Some of the appveyor builds are failing with:
```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: The specified module could not be found.
\\?\C:\projects\opencv4nodejs\build\Release\opencv4nodejs.node
...
```
I think we have to tell the install script to add the opencv bin directory to the system path.

3. Some of the appveyor builds are failing with:
```
opencv4nodejs.obj : error LNK2001: unresolved external symbol "public: static void __cdecl Dnn::Init(class v8::Local<class v8::Object>)" (?Init@Dnn@@SAXV?$Local@VObject@v8@@@v8@@@Z) [C:\projects\opencv4nodejs\build\opencv4nodejs.vcxproj]
C:\projects\opencv4nodejs\build\Release\opencv4nodejs.node : fatal error LNK1120: 1 unresolved externals 
```
I recently fixed this issue with version 2.22.1. Merging the current branch into yours should fix it.

**Pull request merged**
