### PR TITLE
Add img_hash with phash

### PR DESCRIPTION
**Pull request by ht-jo**
I added img_hash module with just only phash since I need it so much. I commented `"cc/xfeatures2d/SIFTDetector.cc"` and related code as https://github.com/justadudewhohacks/opencv4nodejs/issues/805#issuecomment-806314329 in OpenCV 4.5.0. I don't think it is a good way for Pull Request but I believe some guy needs this as a workaround. I want the great maintainer comes up someday and edits this code as well. :)

### CODE REVIEW

**Review by piercus — CHANGES_REQUESTED** [review]
@ht-jo

Thanks for this very good PR that is both : 
* Adding a very important feature
* Is well unit tested

My only concerns are is about a possible regression regarding SIFTdetector, and the CI coverage of OpenCV 4.5
* could you please try to use `if CV_VERSION_LOWER_THAN(4, 0, 0)`in order to keep SIFT Detector (see [example](https://github.com/justadudewhohacks/opencv4nodejs/blob/8aa61e4b17e4a3edb21d4437107eb0357601ff84/cc/imgproc/MatImgproc.cc#L112))
* Also please check my comments on https://github.com/justadudewhohacks/opencv4nodejs/pull/762#issuecomment-1096227832 , i feel opencv 4.5 is not covered by current CI, can you ad it ?

What do you think ?

**Comment by UrielCh** [comment]
nothing in My fork about this PR.

Keep an :eyes: on it.

**Comment by ht-jo** [comment]
@piercus 

Hi. I'm so sorry for replying late. I didn't afford to check this. Ultimately I thought this project had been dead. ;)

I should remind my last work. It has been a while. And I'll look into your comment.

**Comment by UrielCh** [comment]
so that We can close the issue ?

**Comment by piercus** [comment]
@ht-jo Yes this original repo is ... dead.

@UrielCh 's fork is more active, and i would suggest you to create a PR on https://github.com/UrielCh/opencv4nodejs directly

**Pull request closed without merging**
