### PR TITLE
Small fixes for contribution guide

### PR DESCRIPTION
**Pull request by foxxyz**
While following the contribution guide, I noticed a few small issues:
 * Typos on `syncBinding` and `asyncBinding`
 * ~Couldn't find an npm test script for CI as stated, but found the shell script and updated the docs~ incorrect 😑 
 * Added an executable bit to the shell script so it can be invoked directly

Let me know if you're ok with this!

### CODE REVIEW

**Comment by justadudewhohacks** [comment]
Thanks!

`Couldn't find an npm test script for CI as stated, but found the shell script and updated the docs`

What happened when you invoked the test script as specified via npm? `npm run test 3.4.6-contrib 11` should simply call the script via bash command.

**Comment by foxxyz** [comment]
You're right. I'm not sure how I overlooked this... 🤔 

I've removed that part of the doc update, I think the rest is correct.

As an aside, I wish the CI/docker builds could somehow also be called via `npm test` from the `/test` directory, instead of having to go to `/ci/test` first and run `npm test` there, but I don't actually have a good solution for that. Just a thought!

**Comment by justadudewhohacks** [comment]
> As an aside, I wish the CI/docker builds could somehow also be called via npm test from the /test directory, instead of having to go to /ci/test first and run npm test there, but I don't actually have a good solution for that. 

Yeah, I think you would add a script to the base package.json calling the shell script but also setting the current working directory to the ci folder.

**Comment by foxxyz** [comment]
Thank you so much! 🎉

**Pull request merged**
