### PR TITLE
[WIP] Add: photo inpaint

### PR DESCRIPTION
**Pull request by legraphista**
- [x] add `inpaint` bindings (`cv.inpaint`, `cv.inpaintAsync`)
- [x] add typescript descriptors 
- [x] tests

### CODE REVIEW

**Comment by justadudewhohacks** [comment]
Hi,

Can I merge this PR?

**Comment by legraphista** [comment]
Hey @justadudewhohacks! Sorry, I didn't have time to add tests yet for it 😨

**Comment by justadudewhohacks** [comment]
Hi, no need to hurry :), just wasn't sure if you were still working on the branch.

**Comment by legraphista** [comment]
~A few~ _Many_ hours later 😂

**Comment by justadudewhohacks** [comment]
Great stuff!

**Comment by justadudewhohacks** [comment]
Just published version 4.1.0, which includes your contributions.

**Pull request merged**
