### PR TITLE
Add imgproc::warpPerspective

### PR DESCRIPTION
**Pull request by dsanders11**
Nothing too complicated here, should be ready for merge, but a good look over is always a good idea.

### CODE REVIEW

**Comment by justadudewhohacks** [comment]
Hi, thanks for your contribution, but warpPerspective is already implemented [here](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/core/MatImgprocBindings.h#L345-L353).

**Comment by dsanders11** [comment]
@justadudewhohacks, hmm, I'm not sure I understand the difference between `cc/core/MatImgprocBindings.h` and `cc/modules/imageproc/imageprocBindings.h`.

I started the PR because `cv.warpPerspective` is undefined with `opencv4nodejs`. If that's simply a case of it not being exposed in the right place, then that definitely simplifies the PR.

I based my PR off of #551 which defines both `mat.undistort` and `cv.undistortPoints`.

So this PR was attempting to define `cv.warpPerspective` rather than `mat.warpPerspective`.

**Comment by justadudewhohacks** [comment]
Ahh I see. Whenever the first argument of a function binding corresponds to a wrapped class, then we make it a class method of that class to allow chaining: `mat.warpPerspective(...).resize(...)`. The reason why cv.undistortPoints exist is, because you could also pass an array of Point2 instead of a Mat to the function call.

**Comment by dsanders11** [comment]
So will `cv.warpPerspective` never exist then? I'm porting some code and was aiming to keep it as 1:1 as possible.

**Comment by justadudewhohacks** [comment]
It would be reasonable to provide both version, but not by reimplementing the binding altogether. One approach is to check for the first argument being an instance of the class instead of passing "self" of the wrapped class for the non class method binding. But therefore we would have to think of a general solution for all these class method bindings to keep the API consistent.

**Comment by dsanders11** [comment]
Agreed on not duplicating the binding. Since the `MatImgproc` version is really just calling `cv::warpPerspective` with `self` as the first argument, perhaps some refactoring could be done to make this easier.

Off the top of my head, could make a `MatImgprocWorker` which simply wraps another `CatchCvExceptionWorker` and passes everything through to it, but prepends the `self` argument before calling the underlying worker.

Drawbacks to this method include needing to change the signature of methods such as `unwrapRequiredArgs` so that you could use a different type which would allow prepending arguments easily. The other downside is there's a (slightly) unnecessary wrapping of the `self` argument into a `v8::Value` so that the underlying worker sees the arguments the same no matter which version of the call from JS comes in.

```C++
// Small change to IWorker
class IWorker {
public:
  virtual std::string execute() = 0;
  virtual v8::Local<v8::Value> getReturnValue() = 0;
  virtual bool unwrapRequiredArgs(ToBeDeterminedType args) = 0;
  virtual bool unwrapOptionalArgs(ToBeDeterminedType args) = 0;
  virtual bool hasOptArgsObject(ToBeDeterminedType args) = 0;
  virtual bool unwrapOptionalArgsFromOpts(ToBeDeterminedType args) = 0;

  virtual void modifyArgs(ToBeDeterminedType args) {
    // Default implementation is a no-op
  }

  bool applyUnwrappers(Nan::NAN_METHOD_ARGS_TYPE info) {
    ToBeDeterminedType args(info);
    modifyArgs(args);

    return unwrapRequiredArgs(args)
      || (!hasOptArgsObject(args) && unwrapOptionalArgs(args))
      || (hasOptArgsObject(args) && unwrapOptionalArgsFromOpts(args));
  }
};

template <struct Worker>
struct MatImgprocWorker : CatchCvExceptionWorker {
public:
  cv::Mat self;
  Worker worker;

  MatImgprocWorker(cv::Mat mat) {
    this->self = mat;
  }

  void modifyArgs(ToBeDeterminedType args) {
    args.Prepend(Mat::Converter::wrap(this->self));
  }

  std::string executeCatchCvExceptionWorker() {
    return worker.executeCatchCvExceptionWorker();
  }

  v8::Local<v8::Value> getReturnValue() {
    return worker.getReturnValue();
  }
  
  bool unwrapRequiredArgs(ToBeDeterminedType args) {
    return worker.unwrapRequiredArgs(args);
  }

  bool unwrapOptionalArgs(ToBeDeterminedType args) {
    return worker.unwrapOptionalArgs(args);
  }

  bool hasOptArgsObject(ToBeDeterminedType args) {
    return worker.hasOptArgsObject(args);
  }

  bool unwrapOptionalArgsFromOpts(ToBeDeterminedType args) {
    return worker.unwrapOptionalArgsFromOpts(args);
  }
};

// Now it's trivial to support calling methods from both Mat and as top-level functions
typedef MatImgprocWorker<ImgprocBindings::ApplyColorMapWorker> ApplyColorMapWorker;
typedef MatImgprocWorker<ImgprocBindings::WarpPerspectiveWorker> WarpPerspectiveWorker;
```

`ToBeDeterminedType` would replace `Nan::NAN_METHOD_ARGS_TYPE` for the args methods, and a possible implementation would be:

```C++
struct ToBeDeterminedType {
  std::vector<v8::Local<v8::Value>> prependedArgs;
  Nan::NAN_METHOD_ARGS_TYPE info;

  ToBeDeterminedType(Nan::NAN_METHOD_ARGS_TYPE info) {
    this->info = info;
  }

  void Prepend(v8::Local<v8::Value> value) {
    prependedArgs.insert(0, value);
  }
  
  int Length() const { return prependedArgs.length() + info.Length(); }
  v8::Local<v8::Value> operator[](int i) const {
    if (i < prependedArgs.length()) {
        return prependedArgs[i];
    } else {
        return info[i - prependedArgs.length()];
    }
  }
}
```

Just some thoughts on the subject.

**Comment by justadudewhohacks** [comment]
Actually I think this could be much easier with the new CvBinding base that I have been working on the last couple of days. In fact using CvBinding instead of Workers should be the way to implement now, since this is much more straight forward for contributors and less code to write. 

I just merged this into master yesterday with an overworked contribution guide, after you opened the PR, so that was some kind of unfortunate timing.

Anyways, the new binding would look like this:
``` c++
  class WarpPerspective : public CvBinding {
  public:
	  // constructor for cv.warpPerspective(mat, transformationMatrix, ...)
	  WarpPerspective() {
		  auto self = req<Mat::Converter>();
		  WarpPerspective(self->ref());
	  }

	  // constructor for mat.warpPerspective(transformationMatrix, ...)
	  WarpPerspective(cv::Mat self) {
		  auto transformationMatrix = req<Mat::Converter>();
		  auto size = opt<Size::WithCastConverter<cv::Size>>("size", cv::Size());
		  auto flags = opt<FF::IntConverter>("flags", cv::INTER_LINEAR);
		  auto borderMode = opt<FF::IntConverter>("borderMode", cv::BORDER_CONSTANT);
		  auto borderValue = opt<Vec3::Converter>("borderValue", cv::Vec3d());
		  auto warpedMat = ret<Mat::Converter>("warpedMat");

		  executeBinding = [=]() {
			  cv::warpPerspective(self, warpedMat->ref(), transformationMatrix->ref(), size->ref(), flags->ref(), borderMode->ref(), borderValue->ref());
		  };
	  };
  };
```

The first constructor could now be used to instantiate the Binding for the non class method Binding and simply adds a first required argument of whatever type "self" is.

I am currently working on OpenCV 4+ support, once this is done I will try out the above approach.

**Comment by dsanders11** [comment]
> I am currently working on OpenCV 4+ support, once this is done I will try out the above approach.

Sounds good. Looking forward to it. I'll go ahead and close this for the moment and pause my other contributions until that's done.

**Comment by justadudewhohacks** [comment]
Now there is a way to implement this kind of dual binding efficiently using `CvClassMethodBinding`. The syntax of the binding implementation is as follows:

``` c++
class WarpPerspective: public CvClassMethodBinding<Mat> {
public:
    void createBinding(std::shared_ptr<FF::Value<cv::Mat>> self) {
      auto transformationMatrix = req<Mat::Converter>();
      auto size = opt<Size::WithCastConverter<cv::Size>>("size", cv::Size());
      auto flags = opt<FF::IntConverter>("flags", cv::INTER_LINEAR);
      auto borderMode = opt<FF::IntConverter>("borderMode", cv::BORDER_CONSTANT);
      auto borderValue = opt<Vec3::Converter>("borderValue", cv::Vec3d());
      auto warpedMat = ret<Mat::Converter>("warpedMat");

      executeBinding = [=]() {
        cv::warpPerspective(self->ref(), warpedMat->ref(), transformationMatrix->ref(), size->ref(), flags->ref(), borderMode->ref(), borderValue->ref());
      };
    };
};
```

Tests for both the global and class method binding can be generated with `generateClassMethodTests`. I tried to document everything relevant in the [contribution guide](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/CONTRIBUTING.md).

There are still a lot of bindings that have to be refactored this way, so I highly appreciate any kind of contributions. At least the binding you are looking for should be easy to implement now. :)

**Pull request closed without merging**
