### PR TITLE
Issue 480

### PR DESCRIPTION
**Pull request by piercus**
This is about #480 

In GetData, detect when ROI is defined (using `locateROI`) and raise an error when it is defined.

### CODE REVIEW

**Comment by justadudewhohacks** [comment]
Nice one! I wasn't aware of locateROI.

**Comment by MistaLoveCoCo** [comment]
Hey! So I understand this is trying to prevent discrepancy between rows and columns of the image. But how am I supposed to work around this? I am trying to extract a particular region of the image and get the RGBA values of each pixel(through getData() ) of the extracted image.

This is the current situation of my code. Any help would be appreciated. Excuse my poor coding knowledge.

`const matRGBA = imageOrig.channels === 1 ? imageOrig.cvtColor(cv.COLOR_GRAY2RGBA) : imageOrig.cvtColor(cv.COLOR_BGR2RGBA);
   matRGBA.drawRectangle(
        ROI = new cv.Rect( x, y, w, h ),
        new cv.Vec(0, 0, 255),
        3,
        cv.LINE_8
      );
      const region = new cv.Mat(cv.CV_8UC4);
      const regionBuffer = matRGBA.getRegion(ROI).copyTo(region);
      const regionData = region.getData();

      const imgData = new ImageData(
        new Uint8ClampedArray(regionData), regionBuffer.cols, regionBuffer.rows);`

**Comment by MistaLoveCoCo** [comment]
Hey! So I understand this is trying to prevent discrepancy between rows and columns of the image. But how am I supposed to work around this? I am trying to extract a particular region of the image and get the RGBA values of each pixel(through getData() ) of the extracted image.

This is the current situation of my code. Any help would be appreciated. Excuse my poor coding knowledge.

`const matRGBA = imageOrig.channels === 1 ? imageOrig.cvtColor(cv.COLOR_GRAY2RGBA) : imageOrig.cvtColor(cv.COLOR_BGR2RGBA);
matRGBA.drawRectangle(
ROI = new cv.Rect( x, y, w, h ),
new cv.Vec(0, 0, 255),
3,
cv.LINE_8
);
const region = new cv.Mat(cv.CV_8UC4);
const regionBuffer = matRGBA.getRegion(ROI).copyTo(region);
const regionData = region.getData();
  const imgData = new ImageData(
    new Uint8ClampedArray(regionData), regionBuffer.cols, regionBuffer.rows);`

**Comment by MistaLoveCoCo** [comment]
Hey! So I understand this is trying to prevent discrepancy between rows and columns of the image. But how am I supposed to work around this? I am trying to extract a particular region of the image and get the RGBA values of each pixel(through getData() ) of the extracted image.

This is the current situation of my code. Any help would be appreciated. Excuse my poor coding knowledge.

`const matRGBA = imageOrig.channels === 1 ? imageOrig.cvtColor(cv.COLOR_GRAY2RGBA) : imageOrig.cvtColor(cv.COLOR_BGR2RGBA);

matRGBA.drawRectangle(
ROI = new cv.Rect( x, y, w, h ),
new cv.Vec(0, 0, 255),
3,
cv.LINE_8
);

const region = new cv.Mat(cv.CV_8UC4);
const regionBuffer = matRGBA.getRegion(ROI).copyTo(region);
const regionData = region.getData();

  const imgData = new ImageData(
    new Uint8ClampedArray(regionData), regionBuffer.cols, regionBuffer.rows);`

**Pull request merged**
