### PR TITLE
Add: Mat.log

### PR DESCRIPTION
**Pull request by legraphista**
Hi there!
I've added `log` to the `Mat` method list.

### CODE REVIEW

**Comment by legraphista** [comment]
Hmm, I'm not sure why some tests fail for this one. Either opencv's `cv::log` doesn't produce `-inf` for 0, or it's misinterpreted

**Comment by justadudewhohacks** [comment]
Also thanks for this one! By the way `assertDataDeepEquals` is a kind of trashy utitility of mine, which stringifies both arrays with JSON.stringify and compares the string lol... I think this might cause problems with NaN and Infinity values, but not sure ;)

**Comment by legraphista** [comment]
I think the implementation of log/exp in JS is slightly different from the one in opencv/c++ (maybe even depending on platform/compiler), so that values might have ended up very close together, but not actually the exact same, explaining the flakiness of the test.

**Comment by justadudewhohacks** [comment]
Yes, there are also precision differences, as all numbers in JS are doubles, whereas some OpenCV stuff works with floats.

**Comment by justadudewhohacks** [comment]
Your changes have been published with version 3.5.0.

**Pull request merged**
