### PR TITLE
Add `cv.seamlessClone`

### PR DESCRIPTION
**Pull request by foxxyz**
This pull request adds bindings for [`seamlessClone`](https://docs.opencv.org/master/df/da0/group__photo__clone.html#ga2bf426e4c93a6b1f21705513dfeca49d).

I'm on the fence whether this should also exist as a class method of `cv::Mat` or only as a global function. This pull request only implements the latter, due to:
 * Other bindings in the `photo` namespace do not have any `cv::Mat` bindings
 * `seamlessClone` takes multiple `cv::Mat` as input parameters and it would be confusing to figure out which one is being passed in.

Would appreciate your direction on whether class method bindings are also necessary - I'd be happy to add them if so.

Also let me know if you'd prefer additional tests.

### CODE REVIEW

**Comment by justadudewhohacks** [comment]
Thanks for the PR! In general looks good to me.

If you could refactor the worker to use the new CvClassMethodBinding as [GaussianBlur](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/imgproc/imgprocBindings.h#L181-L194) does for example, that would be great! This also allows you to simply export this method as a class method as well as a global method, as described in the contribution guide.

As you figured out, there are no MatPhotoBindings files yet, but you can simply add them.

**Comment by foxxyz** [comment]
Thanks for the quick and detailed feedback!

I've made the changes as suggested - let me know if you'd like to see additional tests or have any other feedback before merge!

**Comment by justadudewhohacks** [comment]
Perfect thanks! Since you now added the class binding, could you also add the seamlessClone typings to [Mat.d.ts](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/lib/typings/Mat.d.ts). 

After that it's ready to merge. :)

**Comment by foxxyz** [comment]
Thanks - I knew I forgot something...! All done.

**Comment by justadudewhohacks** [comment]
Awesome!

**Pull request merged**
