### PR TITLE
Sample app with express & websockets

### PR DESCRIPTION
**Pull request by Mudassir-23**
Sample app with express & WebSockets to live stream video and transformations

### CODE REVIEW

**Comment by Mudassir-23** [comment]
Sample app with express & websockets 
Updated README with new example

**Comment by Mudassir-23** [comment]
Had accidentally closed PR

**Comment by Mudassir-23** [comment]
@justadudewhohacks I have just made edits to Readme, I am not sure why the CI pipeline is breaking. Anyways my changes were to include another example which I had built using opencv4nodejs and have also published an article about the same.  [Article link](https://medium.com/softway-blog/automating-lights-with-computer-vision-nodejs-fb9b614b75b2).

**Comment by justadudewhohacks** [comment]
Hi, thanks for linking your article and the boilerplate! Could you rather put the link to the boilerplate into the example section please. It seems to be a bit off right now, putting it into a new section like that.

Don't worry about the CI, just a download error.

**Comment by Mudassir-23** [comment]
@justadudewhohacks  Thanks for the feedback. I have made the necessary edits as mentioned above by moving boilerplate links into examples and have also submitted a PR.

**Comment by justadudewhohacks** [comment]
Thank you!

**Pull request merged**
